/* Sunstone & Seasons — collection chapter, rotating events, richer shows and companion days. */
const SUNSTONE_IDS=['bunny','barrel','lithops','saguaro','bluetorch','oldman','fairycastle','astrophytum','mooncactus','fishbone','rattail','christmas','peanut','aloe','haworthia','echeveria','dolphins','euphorbia'];
const SUNSTONE_SET=new Set(SUNSTONE_IDS);
const SEASON_CALENDAR=[
  {id:'winter',name:'Moonroom Conservatory',icon:'🌙',months:[11,0,1],reward:'oxalis',color:'#7471a8',challenges:[['care',8,'Complete gentle care'],['play',3,'Play activities'],['glass',1,'Restore a glasshouse room']]},
  {id:'spring',name:'Rainwake Propagation Faire',icon:'🌧️',months:[2,3,4],reward:'sundew',color:'#58a987',challenges:[['propagate',2,'Take cuttings'],['care',8,'Care for plants'],['play',2,'Play activities']]},
  {id:'summer',name:'Sunstone Solstice',icon:'☀️',months:[5,6,7],reward:'astrophytum',color:'#d5963f',challenges:[['sunstone',2,'Welcome desert plants'],['care',8,'Care for plants'],['show',1,'Enter a plant show']]},
  {id:'autumn',name:'Lantern Leaf Festival',icon:'🏮',months:[8,9,10],reward:'rex',color:'#b66b55',challenges:[['photo',3,'Take plant portraits'],['show',2,'Enter plant shows'],['seed',2,'Open surprise seeds']]},
];
const SHOW_CATEGORIES=[
  {id:'desert',name:'Desert Architecture',icon:'🌵',tags:['sunstone','cactus','euphorbia','columnar','globular'],zone:'sun',desc:'Silhouette, symmetry and sun-grown character.'},
  {id:'jewel',name:'Living Jewels',icon:'💎',tags:['succulent','rosette','spotted','striped','iridescent'],zone:'sun',desc:'Colour, pattern and immaculate compact form.'},
  {id:'velvet',name:'Velvet & Vein',icon:'🖤',tags:['velvet','dramatic','nightfold'],zone:'shade',desc:'Texture, venation and moonlit depth.'},
  {id:'bloom',name:'Trail & Bloom',icon:'🌸',tags:['flowers','trailing','epiphyte'],zone:'bright',desc:'Movement, bloom and graceful presentation.'},
  {id:'oddity',name:'Botanical Oddities',icon:'🌀',tags:['weird','carnivore','grafted','fenestrates'],zone:'cabinet',desc:'The stranger and more storied, the better.'},
];

function ensureExpansion(){
  sequelDefaults();
  if(!S.sequel.events)S.sequel.events={};
  if(!S.sequel.sunstoneClaims)S.sequel.sunstoneClaims=[];
  if(!S.sequel.showRecords)S.sequel.showRecords={};
  if(!S.sequel.companionDays)S.sequel.companionDays={};
  if(!S.sequel.weatherDay)S.sequel.weatherDay='';
}
const previousSequelDefaults=sequelDefaults;
sequelDefaults=function(){previousSequelDefaults();if(S){if(!S.sequel.events)S.sequel.events={};if(!S.sequel.sunstoneClaims)S.sequel.sunstoneClaims=[];if(!S.sequel.showRecords)S.sequel.showRecords={};if(!S.sequel.companionDays)S.sequel.companionDays={}}};
function currentSeason(){const m=new Date().getMonth();return SEASON_CALENDAR.find(x=>x.months.includes(m))||SEASON_CALENDAR[0]}
function eventKey(e=currentSeason()){return `${new Date().getFullYear()}-${e.id}`}
function eventState(e=currentSeason()){ensureExpansion();const key=eventKey(e);if(!S.sequel.events[key])S.sequel.events[key]={progress:{},claimed:false};return S.sequel.events[key]}
function seasonAction(type,n=1){const e=currentSeason(),st=eventState(e),alias={water:'care',feed:'care'}[type]||type;const ch=e.challenges.find(x=>x[0]===alias);if(!ch)return;st.progress[alias]=Math.min(ch[1],(st.progress[alias]||0)+n);save()}
function seasonTotal(e=currentSeason()){const st=eventState(e);return e.challenges.reduce((a,c)=>a+Math.min(c[1],st.progress[c[0]]||0),0)}
function seasonTarget(e=currentSeason()){return e.challenges.reduce((a,c)=>a+c[1],0)}
function seasonSummary(){return `${seasonTotal()}/${seasonTarget()}`}
function isSunstoneSpecies(sp){return !!sp&&(SUNSTONE_SET.has(sp.id)||sp.tags.includes('sunstone'))}
function sunstoneCount(){ensureExpansion();return SUNSTONE_IDS.filter(id=>S.dex[id]).length}
function gardenAtmosphere(){const d=sequelDay(),seed=[...d].reduce((a,c)=>a+c.charCodeAt(0),0),weather=['clear','breeze','rain','mist'][seed%4],night=new Date().getHours()<7||new Date().getHours()>=19;return{className:`weather-${weather}${night?' world-night':''}`,label:{clear:'☀️ Clear & warm',breeze:'🍃 Soft breeze',rain:'🌧️ Garden rain',mist:'🌫️ Glasshouse mist'}[weather]+(night?' · moonlit':'')}}

const baseRollMarket=rollMarket;
rollMarket=function(){baseRollMarket();const event=currentSeason(),pool=SPECIES.filter(sp=>event.id==='summer'?isSunstoneSpecies(sp):event.id==='winter'?(sp.tags.includes('nightfold')||sp.light==='shade'):event.id==='spring'?(sp.tags.includes('humidity')||sp.tags.includes('flowers')):(sp.tags.includes('dramatic')||sp.tags.includes('variegated')));const featured=[];while(featured.length<2&&pool.length){const sp=pick(pool.filter(x=>!featured.includes(x)));if(!sp)break;featured.push(sp)}featured.forEach((sp,i)=>{const leaves=1+Math.floor(Math.random()*3);S.market[i]={key:`event_${sp.id}_${now()}_${i}`,speciesId:sp.id,varieg:sp.forceVar||'none',leaves,price:Math.round(sp.value*RARITY[sp.rarity].mult*(.92+leaves*.12))}})};
const baseRenderShop=renderShop;
renderShop=function(){baseRenderShop();if(shopTab!=='plants')return;const tabs=$('#screen-shop .tabs'),e=currentSeason();if(tabs)tabs.insertAdjacentHTML('afterend',`<button class="market-feature" data-sequel="season"><b>${e.icon} ${e.name} featured grower</b><span>Two event plants are guaranteed in every refresh · Sunstone discoveries ${sunstoneCount()}/18</span></button>`)};

function seasonModal(){const e=currentSeason(),st=eventState(e),total=seasonTotal(e),target=seasonTarget(e);modal(`<h3>${e.icon} Seasonal Calendar</h3><div class="season-calendar">${SEASON_CALENDAR.map(x=>`<div class="${x.id===e.id?'on':''}"><b>${x.icon} ${x.name}</b><small>${x.months.map(m=>['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][m]).join(' · ')}</small></div>`).join('')}</div><h3>${e.name}</h3><p>Seasonal progress never resets from a missed day. Complete each real garden challenge before the calendar turns.</p><div class="season-challenges">${e.challenges.map(c=>{const p=st.progress[c[0]]||0;return `<div><span>${p>=c[1]?'✓':'○'} ${c[2]}</span><b>${p}/${c[1]}</b><i><em style="width:${p/c[1]*100}%"></em></i></div>`}).join('')}</div><button class="btn gold" id="claimEvent" ${total>=target&&!st.claimed?'':'disabled'}>${st.claimed?'Season reward claimed':`Claim ${SPECIES_BY_ID[e.reward].name}`}</button>`);if(total>=target&&!st.claimed)$('#claimEvent').onclick=()=>{const z=anyFreeSlot();if(!z)return toast('Make one garden slot before claiming.','bad');newPlant(e.reward,{zone:z,leaves:3});st.claimed=true;S.sequel.legacy++;save();closeModal();sparkle(e.icon,24);toast(`${SPECIES_BY_ID[e.reward].name} joins the seasonal collection!`,'gold');renderGarden()}}

function showScore(p,cat){const sp=SPECIES_BY_ID[p.speciesId],health=Math.round(p.health*.25),maturity=Math.round(Math.min(1,p.leaves.length/sp.maxLeaves)*25),rarity=RARITY[effectiveRarity(p)].order*5,theme=sp.tags.some(t=>cat.tags.includes(t))?25:0,placement=p.zone===cat.zone?8:0,legacy=S.sequel.favoriteIds.includes(p.id)?5:0,varieg=bestVarOf(p)!=='none'?4:0;return{total:health+maturity+rarity+theme+placement+legacy+varieg,health,maturity,rarity,theme,placement,legacy,varieg}}
function showModal(selected){ensureExpansion();const day=sequelDay();if(!selected){const rotation=SHOW_CATEGORIES.filter((_,i)=>(i+new Date().getDate())%2===0).slice(0,3);return modal(`<h3>♕ Today’s Royal Plant Show</h3><p>Each category can award one full prize per day. Choose where your collection tells its best story.</p><div class="showcategories">${rotation.map(c=>`<button data-show-category="${c.id}"><b>${c.icon} ${c.name}</b><span>${c.desc}</span><i>${S.sequel.showRecords[`${day}:${c.id}`]||'unjudged'}</i></button>`).join('')}</div>`)}const cat=SHOW_CATEGORIES.find(x=>x.id===selected);modal(`<h3>${cat.icon} ${cat.name}</h3><p>${cat.desc} Matching form and the ${ZONES[cat.zone].name} earn category points.</p><div class="showchoices">${S.plants.map(p=>{const sc=showScore(p,cat),sp=SPECIES_BY_ID[p.speciesId];return `<button data-show-entry="${p.id}" data-category="${cat.id}">${renderPlant(p,{tag:'show'+p.id})}<b>${esc(p.nick||sp.name)}</b><small>estimated ${sc.total}</small></button>`}).join('')}</div>`)}
function judgeShow(p,cat){const score=showScore(p,cat),key=`${sequelDay()}:${cat.id}`,previous=S.sequel.showRecords[key]||0,first=!previous;S.sequel.showRecords[key]=Math.max(previous,score.total);S.sequel.showWins++;seasonAction('show',1);bumpQuest('show',1);let reward=first?(score.total>=90?220:score.total>=72?130:55):Math.max(10,Math.round((score.total-previous)/2));S.coins+=reward;if(first&&score.total>=90){S.gems++;S.sequel.legacy++}save();closeModal();sparkle(score.total>=90?'🏆':'🎗️',20);modal(`<h3>${score.total>=90?'🏆 Best in Category':score.total>=72?'🎗️ Royal Ribbon':'A promising entry'} · ${score.total}</h3><div class="scorebreak"><span>Health <b>${score.health}</b></span><span>Maturity <b>${score.maturity}</b></span><span>Rarity <b>${score.rarity}</b></span><span>Theme <b>${score.theme}</b></span><span>Placement <b>${score.placement}</b></span><span>Legacy & traits <b>${score.legacy+score.varieg}</b></span></div><p>Reward: <b>${reward}🪙${first&&score.total>=90?' + 1💎 + 1◈':''}</b></p><button class="btn" data-close="1">Return to the garden</button>`)}

const SUNSTONE_MILESTONES=[{n:3,name:'Desert Beginner',reward:'250🪙'},{n:7,name:'Shape Collector',reward:'2💎 + Variegation Dust'},{n:12,name:'Living Jewel Curator',reward:'Star Cactus specimen'},{n:18,name:'Sunstone Royal Botanist',reward:'Saguaro + 3◈'}];
function sunstoneModal(){ensureExpansion();const count=sunstoneCount();modal(`<h3>🌵 Sunstone Almanac · ${count}/18</h3><p>Columnar giants, globular jewels, jointed epiphytes and sculptural succulents each ask for different light and care.</p><div class="sunstone-grid">${SUNSTONE_IDS.map(id=>{const sp=SPECIES_BY_ID[id],seen=!!S.dex[id];return `<div class="${seen?'seen':'locked'}">${renderPlant({id:9900+SUNSTONE_IDS.indexOf(id),speciesId:id,potId:'terra',path:sp.light,shading:'matte',health:100,water:80,growth:0,leaves:[{seed:900+SUNSTONE_IDS.indexOf(id),len:58,fen:0,varieg:'none',unfurl:1}]},{tag:'almanac'})}<b>${seen?sp.name:'Unknown specimen'}</b><small>${seen?`${RARITY[sp.rarity].name} · ${ZONES[sp.light].name}`:'Find it at the seasonal market'}</small></div>`}).join('')}</div><div class="milestones">${SUNSTONE_MILESTONES.map(m=>`<div><span><b>${m.n} · ${m.name}</b><small>${m.reward}</small></span><button class="btn sm" data-sunstone-claim="${m.n}" ${count>=m.n&&!S.sequel.sunstoneClaims.includes(m.n)?'':'disabled'}>${S.sequel.sunstoneClaims.includes(m.n)?'Claimed':'Claim'}</button></div>`).join('')}</div>`)}
function claimSunstone(n){const m=SUNSTONE_MILESTONES.find(x=>x.n===n);if(!m||sunstoneCount()<n||S.sequel.sunstoneClaims.includes(n))return;if(n===3)S.coins+=250;if(n===7){S.gems+=2;S.dust=true}if(n===12||n===18){const z=anyFreeSlot();if(!z)return toast('Make one garden slot before claiming the specimen.','bad');newPlant(n===12?'astrophytum':'saguaro',{zone:z,leaves:3})}if(n===18)S.sequel.legacy+=3;S.sequel.sunstoneClaims.push(n);save();sparkle('🌵',22);sunstoneModal();toast(`${m.name} reward claimed.`,'gold')}

function companionMoment(name){ensureExpansion();const key=`${sequelDay()}:${name}`;if(S.sequel.companionDays[key])return toast(`${name} has already shared today’s garden adventure.`);S.sequel.companionDays[key]=true;if(name==='Joey'){S.coins+=55;toast('Joey found a fallen seed packet by the meadow. +55🪙','gold')}if(name==='Salem'){const pest=S.plants.find(p=>p.pests);if(pest){pest.pests=false;toast(`Salem spotted the pests on ${pest.nick||plantName(pest)}. Crisis averted.`)}else{S.inv.neem=(S.inv.neem||0)+1;toast('Salem guarded the greenhouse and earned a Neem Spray.')}}if(name==='Trace'){S.gems++;S.sequel.visitors.push({at:now(),name:'Trace',text:'Trace left a pawprint beside the warmest pond stone.'});toast('Trace uncovered a visitor token beneath the pond stone. +1💎','gold')}seasonAction('companion',1);bumpQuest('companion',1);save();renderTop()}

const priorSecondsPerLeaf=secondsPerLeaf;
secondsPerLeaf=function(p){let base=priorSecondsPerLeaf(p),sp=SPECIES_BY_ID[p.speciesId],a=gardenAtmosphere();if(S.sequel.glassRooms>=1&&sp.tags.includes('humidity'))base*=.9;if(S.sequel.glassRooms>=2&&(sp.tags.includes('nightfold')||sp.light==='shade')&&a.className.includes('world-night'))base*=.88;if(S.sequel.secret&&p.hybrid)base*=.82;if(a.className.includes('weather-rain')&&sp.tags.includes('humidity'))base*=.92;if(a.className.includes('weather-clear')&&isSunstoneSpecies(sp))base*=.92;return base};

[['sunstone1','Welcome a Sunstone plant',1,'sunstone',120,35],['show1','Enter a plant show',1,'show',100,30],['friend1','Share a moment with a companion',1,'companion',70,20]].forEach(q=>{if(!QUEST_POOL.some(x=>x.id===q[0]))QUEST_POOL.push({id:q[0],text:q[1],goal:q[2],type:q[3],coins:q[4],xp:q[5]})});
const priorBuyPlant=A.buyPlant;A.buyPlant=function(o){const sp=SPECIES_BY_ID[o?.speciesId],r=priorBuyPlant.call(A,o);if(r===true&&isSunstoneSpecies(sp)){seasonAction('sunstone',1);bumpQuest('sunstone',1)}return r};
const priorCutting=A.cutting;A.cutting=function(p){const r=priorCutting.call(A,p);if(r===true)seasonAction('propagate',1);return r};
const priorArcadeReward=A.arcadeReward;A.arcadeReward=function(result){const r=priorArcadeReward.call(A,result);seasonAction('play',1);return r};
['water','feed','photo'].forEach(kind=>{const prior=A[kind];A[kind]=function(p){const r=prior.call(A,p);if(r===true||typeof r==='number')seasonAction(kind,1);return r}});
const priorJournalExpansion=renderJournal;renderJournal=function(){priorJournalExpansion();const root=$('#screen-journal');root.insertAdjacentHTML('afterbegin',`<button class="collection-banner" data-expansion="sunstone"><b>🌵 Sunstone Almanac · ${sunstoneCount()}/18</b><span>${sunstoneCount()>=18?'Royal desert collection complete':'New silhouettes and collector rewards await'}</span></button><button class="collection-banner season" data-sequel="season"><b>${currentSeason().icon} ${currentSeason().name}</b><span>${seasonSummary()} seasonal actions complete</span></button>`)};

const priorExpansionWire=wire;wire=function(){priorExpansionWire();$('#screens').addEventListener('click',e=>{const cat=e.target.closest('[data-show-category]');if(cat)showModal(cat.dataset.showCategory);const entry=e.target.closest('[data-show-entry]');if(entry)judgeShow(S.plants.find(p=>p.id===+entry.dataset.showEntry),SHOW_CATEGORIES.find(c=>c.id===entry.dataset.category));const claim=e.target.closest('[data-sunstone-claim]');if(claim)claimSunstone(+claim.dataset.sunstoneClaim)});$('#modal').addEventListener('click',e=>{const cat=e.target.closest('[data-show-category]');if(cat)showModal(cat.dataset.showCategory);const entry=e.target.closest('[data-show-entry]');if(entry)judgeShow(S.plants.find(p=>p.id===+entry.dataset.showEntry),SHOW_CATEGORIES.find(c=>c.id===entry.dataset.category));const claim=e.target.closest('[data-sunstone-claim]');if(claim)claimSunstone(+claim.dataset.sunstoneClaim);if(e.target.closest('[data-close]'))closeModal()})};
